/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package C_Presentacion;

import java.awt.BorderLayout;

/**
 *
 * @author IsmaelUbiera
 */
public class PanelProductos extends javax.swing.JPanel {

    /**
     * Creates new form PanelProductos
     */
    public PanelProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSLabelHoraBeanInfo1 = new rojeru_san.RSLabelHoraBeanInfo();
        rSLabelFechaBeanInfo1 = new rojeru_san.RSLabelFechaBeanInfo();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnDepartamentos = new javax.swing.JButton();
        btnVentasPeriodo = new javax.swing.JButton();
        btnPromociones = new javax.swing.JButton();
        btnCatalogo = new javax.swing.JButton();
        PanelContenedorProductos = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Productos");

        btnNuevo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-add_list_32px.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-edit_property_32px.png"))); // NOI18N
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnEliminarProducto.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-waste_32px.png"))); // NOI18N
        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        btnDepartamentos.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnDepartamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-warehouse_32px.png"))); // NOI18N
        btnDepartamentos.setText("Departamentos");
        btnDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentosActionPerformed(evt);
            }
        });

        btnVentasPeriodo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnVentasPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-date_span_32px.png"))); // NOI18N
        btnVentasPeriodo.setText("Ventas por Periodo");
        btnVentasPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasPeriodoActionPerformed(evt);
            }
        });

        btnPromociones.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnPromociones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-discount_32px.png"))); // NOI18N
        btnPromociones.setText("Promociones");
        btnPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromocionesActionPerformed(evt);
            }
        });

        btnCatalogo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-magazine_32px.png"))); // NOI18N
        btnCatalogo.setText("Catalogo");
        btnCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoActionPerformed(evt);
            }
        });

        PanelContenedorProductos.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout PanelContenedorProductosLayout = new javax.swing.GroupLayout(PanelContenedorProductos);
        PanelContenedorProductos.setLayout(PanelContenedorProductosLayout);
        PanelContenedorProductosLayout.setHorizontalGroup(
            PanelContenedorProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelContenedorProductosLayout.setVerticalGroup(
            PanelContenedorProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDepartamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVentasPeriodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPromociones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCatalogo)
                .addGap(0, 461, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelContenedorProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(jButton2)
                    .addComponent(btnEliminarProducto)
                    .addComponent(btnDepartamentos)
                    .addComponent(btnVentasPeriodo)
                    .addComponent(btnPromociones)
                    .addComponent(btnCatalogo))
                .addGap(18, 18, 18)
                .addComponent(PanelContenedorProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoActionPerformed
        // TODO add your handling code here:
        PanelCatalogoProductos PCatalogoProductos = new PanelCatalogoProductos(); 
        PCatalogoProductos.setSize(1417,600); //Size PanelClientes
        PCatalogoProductos.setLocation(5, 5);
        
        PanelContenedorProductos.removeAll();
        PanelContenedorProductos.add(PCatalogoProductos,BorderLayout.CENTER);
        PanelContenedorProductos.revalidate();
        PanelContenedorProductos.repaint();
        
    }//GEN-LAST:event_btnCatalogoActionPerformed

    private void btnPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromocionesActionPerformed
        // TODO add your handling code here:
        PanelPromociones PPromociones = new PanelPromociones(); 
        PPromociones.setSize(1417,600); //Size PanelClientes
        PPromociones.setLocation(5, 5);
        
        PanelContenedorProductos.removeAll();
        PanelContenedorProductos.add(PPromociones,BorderLayout.CENTER);
        PanelContenedorProductos.revalidate();
        PanelContenedorProductos.repaint();
    }//GEN-LAST:event_btnPromocionesActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        // TODO add your handling code here:
        PanelEliminarProducto PElimininarProductos = new PanelEliminarProducto(); 
        PElimininarProductos.setSize(1417,600); //Size PanelClientes
        PElimininarProductos.setLocation(5, 5);
        
        PanelContenedorProductos.removeAll();
        PanelContenedorProductos.add(PElimininarProductos,BorderLayout.CENTER);
        PanelContenedorProductos.revalidate();
        PanelContenedorProductos.repaint();
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentosActionPerformed
        // TODO add your handling code here:
        PanelDepartamentos PDepartamentos = new PanelDepartamentos(); 
        PDepartamentos.setSize(1417,600); //Size PanelClientes
        PDepartamentos.setLocation(5, 5);
        
        PanelContenedorProductos.removeAll();
        PanelContenedorProductos.add(PDepartamentos,BorderLayout.CENTER);
        PanelContenedorProductos.revalidate();
        PanelContenedorProductos.repaint();
    }//GEN-LAST:event_btnDepartamentosActionPerformed

    private void btnVentasPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasPeriodoActionPerformed
        // TODO add your handling code here:
        PanelPeriodoProducto PPeriodoProducto = new PanelPeriodoProducto(); 
        PPeriodoProducto.setSize(1417,600); //Size PanelClientes
        PPeriodoProducto.setLocation(5, 5);
        
        PanelContenedorProductos.removeAll();
        PanelContenedorProductos.add(PPeriodoProducto,BorderLayout.CENTER);
        PanelContenedorProductos.revalidate();
        PanelContenedorProductos.repaint();
    }//GEN-LAST:event_btnVentasPeriodoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        PanelNuevoProducto PNuevoProducto = new PanelNuevoProducto(); 
        PNuevoProducto.setSize(1417,600); //Size PanelClientes
        PNuevoProducto.setLocation(5, 5);
        
        PanelContenedorProductos.removeAll();
        PanelContenedorProductos.add(PNuevoProducto,BorderLayout.CENTER);
        PanelContenedorProductos.revalidate();
        PanelContenedorProductos.repaint();
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedorProductos;
    private javax.swing.JButton btnCatalogo;
    private javax.swing.JButton btnDepartamentos;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPromociones;
    private javax.swing.JButton btnVentasPeriodo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private rojeru_san.RSLabelFechaBeanInfo rSLabelFechaBeanInfo1;
    private rojeru_san.RSLabelHoraBeanInfo rSLabelHoraBeanInfo1;
    // End of variables declaration//GEN-END:variables
}
